# Generated by Django 5.1.1 on 2024-09-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_rename_name_item_item_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="add_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
