# Generated by Django 5.1.1 on 2024-09-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_item_add_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="up_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="add_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
